services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-username/e-pks}:latest
    container_name: e_pks_app
    restart: unless-stopped
    working_dir: /var/www/e-pks
    ports:
      - "9001:9000"
    volumes:
      - ./.env:/var/www/e-pks/.env
      - ./storage/app/public:/var/www/e-pks/storage/app/public
      - ./storage/logs:/var/www/e-pks/storage/logs
    networks:
      - e_pks_network

networks:
  e_pks_network:
    driver: bridge
